[watch]
ignore = [
    # The Leptonic build writes these files. Not ignoring them could lead to infinite rebuilds when using `trunk serve`.
    "./public/js",
    # The Leptonic build writes these files. Not ignoring them could lead to infinite rebuilds when using `trunk serve`.
    "./style/leptonic",
    "./src-tauri",
]

[serve]
address = "0.0.0.0"
port = 1420
open = false
ws_protocol = "ws"
